### ISSUE TITLE
Create release checklist

### ISSUE THREAD

**Issue by mikemhenry** [OpenFreeEnergy/openfe#623]
Should document:
1. Decide to create release (collaborate with upstream and downstream) and ensure no api breaks (unless major) (decide if an RC is needed)
2. Make upcoming release announcement to key stakeholders   
1. Create branch from `main` called `release/version` ie `release/0.89.3`
2. Test the branch, if changes are needed, make PR into the branch
3. After branch is validated, create release notes and add deprecation warnings if needed 
4. create tag
5. evaluate conda-forge pins
1. release branch on conda-forge, make single file installer(s), make docker and apptainer images
5. merge branch back into main (or cheery pick), deal with merge conflicts so post merge we have something that works
1. Make announcement to the world

**Comment by IAlibay** [comment]
Key stakeholders:
- OpenFE internal team
- OpenFE board
- OpenFE developers (e.g. FEFlow)
- OpenFE direct users / collaborators
- OpenFF
- Alchemiscale
- ASAP
- General community (linkedin, etc...)

**Comment by mikemhenry** [comment]
Make cannery CI workflows for key downstream (alchemiscale, feflow)

**Comment by IAlibay** [comment]
TODO:
- [ ] Document - where does this checklist live?
- [ ] Define what testing the branch means

**Comment by mikemhenry** [comment]
TODO
- [ ] Make PR to add this to docs
- [ ] Migrate how to cut release from wiki

**Comment by IAlibay** [comment]
If we're making a minor release this sprint, we should try to get this written somewhere.
