### ISSUE TITLE
Get macos-12+, including osx-arm64 (i.e. macos-latest) runners working in CI

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe#842]
Follow-up from https://github.com/OpenFreeEnergy/openfe/pull/841#pullrequestreview-2022068366

**Comment by IAlibay** [comment]
## Overview of issue

* macos-13 (x86_64) is not compatible with the current conda-forge deployments of AT22 or AT23. The wheels will get picked up and installed, but SQM will fail
* macos-14 (osx-arm64) does not have compatible AmberTools wheels

## TODO:

- [ ] unpin openfe CI
- [ ] unpin gufe CI
- [ ] unpin ExampleNotebooks CI
- [ ] ...

**Comment by IAlibay** [comment]
This has either been addressed or moved to other issues.

The lack of compatibility between AT and macos-13 is an issue that will need a look at.

**Comment by atravitz** [comment]
> This has either been addressed or moved to other issues.
> 
> The lack of compatibility between AT and macos-13 is an issue that will need a look at.

@mikemhenry do you know if any recent ambertools builds are compatible with macos-13? If not, we will drop our support of macos-13 as well.

**Comment by mikemhenry** [comment]
That is a good question, recent versions no, but older versions yes?  I think the easiest way to check is to see if an env will solve os macos-13 with ambertools 22, 23, or 24. You might need to check python versions 3.9-3.12, since there might be a sweet spot where it all algins.

**Comment by IAlibay** [comment]
@mikemhenry the issue isn't so much that it doesn't resolve but that there's an issue with the binary - i.e. if you run SQM it'll fail horribly.

**Comment by mikemhenry** [comment]
We now have enough ambertools23 and ambertools24 builds for osx-arm64 so that we can get away with just testing `macos-14` aka `macos-latest` (and we dropped support for intel macs anyway).

```
        os: ["ubuntu-latest"]
        pydantic-version: [">1"]
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
        openeye: ["no"]
        include:
          - os: "macos-latest"
            python-version: "3.12"
            pydantic-version: ">1"
          - os: "ubuntu-latest"
            python-version: "3.11"
            pydantic-version: "<2"
          - os: "ubuntu-latest"
            python-version: "3.11"
            pydantic-version: ">1"
            openeye: "yes"
          - os: "macos-latest"
            python-version: "3.12"
            pydantic-version: ">1"
            omff-version: ">0.13"
            openeye: ["no"]
```
